### ISSUE TITLE
Question about Table 3 in the paper.

### ISSUE THREAD

**Issue by misoyuri** [dominickrei/Limited-data-vits#3]
Hi, I have a question about Table 3 in the paper.

In Table 3, you compare SSL + FT and your SSAT performance.
However, I could not find which SSL is used.

In SSL + FT, did you use MAE?

**Comment by dominickrei** [comment]
Hello, thank you for your interest!

You are correct, the SSL+FT results in Table 3 use MAE as the SSL technique.
